import {
  Inquiry,
  Booking,
  Payment,
  Customer,
  Review,
  ConciergeStaff,
  RBACMatrixDomain,
  IntegrationStatus,
} from '../types'

export const mockIntegrationStatus: IntegrationStatus = {
  supabase: { status: 'Online', latency: '24ms', region: 'Mumbai (ap-south-1)' },
  razorpay: { status: 'Active', sync: '99.98% Sync', liveKey: 'rzp_live_98a7F201vLk9Q' },
  whatsappBot: { status: 'Connected', uptime: '99.2%', businessNumber: '+91 98112 40992' },
  webhookHealth: { status: 'Status 200 OK', desyncs: 0 },
}

export const mockStaffList: ConciergeStaff[] = [
  {
    id: 'staff-01',
    name: 'Devendra Rao',
    role: 'Super Admin',
    email: 'devendra.rao@aarivavoyages.com',
    phone: '+91 98201 44892',
    regional_hub: 'Kashmir',
    two_factor: { enabled: true, method: 'FIDO2' },
    last_pulse: 'Active now',
    status: 'Active',
    avatar: 'DR',
    permissions_tier: 'Tier 0 - Apex Authority',
  },
  {
    id: 'staff-02',
    name: 'Aaditya Vikram Singhania',
    role: 'Super Admin',
    email: 'aaditya.v@aarivavoyages.com',
    phone: '+91 98110 33119',
    regional_hub: 'Rajasthan',
    two_factor: { enabled: true, method: 'FIDO2' },
    last_pulse: '14m ago',
    status: 'Active',
    avatar: 'AV',
    permissions_tier: 'Tier 0 - Operations Lead',
  },
  {
    id: 'staff-03',
    name: 'Zahoor Wani',
    role: 'Super Admin',
    email: 'zahoor.w@aarivavoyages.com',
    phone: '+91 94190 22814',
    regional_hub: 'Kashmir',
    two_factor: { enabled: true, method: 'TOTP' },
    last_pulse: '28m ago',
    status: 'Active',
    avatar: 'ZW',
    permissions_tier: 'Tier 0 - Charter Operations',
  },
  {
    id: 'staff-04',
    name: 'Priya Sharma',
    role: 'Lead Concierge',
    email: 'priya.sharma@aarivavoyages.com',
    phone: '+91 98118 77231',
    regional_hub: 'Rajasthan',
    two_factor: { enabled: true, method: 'TOTP' },
    last_pulse: '2m ago',
    status: 'Active',
    avatar: 'PS',
    permissions_tier: 'Tier 2 - Lead Concierge',
  },
  {
    id: 'staff-05',
    name: 'Tariq Ahmad Mir',
    role: 'Lead Concierge',
    email: 'tariq.mir@aarivavoyages.com',
    phone: '+91 94191 88203',
    regional_hub: 'Kashmir',
    two_factor: { enabled: true, method: 'TOTP' },
    last_pulse: 'Active now',
    status: 'Active',
    avatar: 'TM',
    permissions_tier: 'Tier 2 - Lead Concierge',
  },
  {
    id: 'staff-06',
    name: 'Ananya Nambiar',
    role: 'Lead Concierge',
    email: 'ananya.n@aarivavoyages.com',
    phone: '+91 98470 55198',
    regional_hub: 'Kerala',
    two_factor: { enabled: true, method: 'TOTP' },
    last_pulse: '6m ago',
    status: 'Active',
    avatar: 'AN',
    permissions_tier: 'Tier 2 - Lead Concierge',
  },
  {
    id: 'staff-07',
    name: 'Kabir Fernandes',
    role: 'Lead Concierge',
    email: 'kabir.f@aarivavoyages.com',
    phone: '+91 98311 00293',
    regional_hub: 'Andaman',
    two_factor: { enabled: true, method: 'TOTP' },
    last_pulse: '45m ago',
    status: 'Active',
    avatar: 'KF',
    permissions_tier: 'Tier 2 - Lead Concierge',
  },
  {
    id: 'staff-08',
    name: 'Meenakshi Sundaram',
    role: 'Finance & Escrow',
    email: 'meenakshi.s@aarivavoyages.com',
    phone: '+91 98402 11985',
    regional_hub: 'Kerala',
    two_factor: { enabled: true, method: 'FIDO2' },
    last_pulse: '5m ago',
    status: 'Active',
    avatar: 'MS',
    permissions_tier: 'Tier 1 - Financial Controller',
  },
  {
    id: 'staff-09',
    name: 'Rohan Deshmukh',
    role: 'Finance & Escrow',
    email: 'rohan.d@aarivavoyages.com',
    phone: '+91 98205 33901',
    regional_hub: 'Rajasthan',
    two_factor: { enabled: true, method: 'TOTP' },
    last_pulse: '1h ago',
    status: 'Active',
    avatar: 'RD',
    permissions_tier: 'Tier 1 - Escrow Settlement',
  },
  {
    id: 'staff-10',
    name: 'Farooq Lone',
    role: 'Lead Concierge',
    email: 'farooq.lone@aarivavoyages.com',
    phone: '+91 94192 11776',
    regional_hub: 'Kashmir',
    two_factor: { enabled: true, method: 'TOTP' },
    last_pulse: '18m ago',
    status: 'Active',
    avatar: 'FL',
    permissions_tier: 'Tier 2 - Lead Concierge',
  },
  {
    id: 'staff-11',
    name: 'Deepika Iyer',
    role: 'Lead Concierge',
    email: 'deepika.i@aarivavoyages.com',
    phone: '+91 98409 66213',
    regional_hub: 'Kerala',
    two_factor: { enabled: true, method: 'TOTP' },
    last_pulse: '12m ago',
    status: 'Active',
    avatar: 'DI',
    permissions_tier: 'Tier 2 - Lead Concierge',
  },
  {
    id: 'staff-12',
    name: 'Gaurav Khandelwal',
    role: 'Finance & Escrow',
    email: 'gaurav.k@aarivavoyages.com',
    phone: '+91 98290 44102',
    regional_hub: 'Rajasthan',
    two_factor: { enabled: true, method: 'TOTP' },
    last_pulse: '34m ago',
    status: 'Active',
    avatar: 'GK',
    permissions_tier: 'Tier 1 - Audit & Reconciliation',
  },
]

export const mockRBACMatrix: RBACMatrixDomain[] = [
  {
    domain: 'Guest Dossiers & PII',
    superAdmin: 'Full Read/Write/Export',
    leadConcierge: 'View & Edit Dossier',
    finance: 'Masked PII Only',
  },
  {
    domain: 'Razorpay Refunds & Escrow',
    superAdmin: 'Unlimited Authority',
    leadConcierge: '❌ No Escrow Access',
    finance: 'Policy Payouts Only',
  },
  {
    domain: 'Transaction Cap (High-value transfers)',
    superAdmin: 'Unlimited (₹∞)',
    leadConcierge: 'Up to ₹5,00,000',
    finance: 'Up to ₹25,00,000',
  },
  {
    domain: 'Booking Modifications & Waivers',
    superAdmin: '✓ Instant Waiver',
    leadConcierge: '✓ Requires Approval',
    finance: '❌ Read Only',
  },
  {
    domain: 'Sanity CMS Publishing',
    superAdmin: '✓ Live Production Purge',
    leadConcierge: '❌ Draft Staging Only',
    finance: '✓ Read & Financial Audit',
  },
  {
    domain: 'WhatsApp VIP Broadcast',
    superAdmin: '✓ Full Meta Broadcast',
    leadConcierge: 'Transfer PNR Only',
    finance: '❌ Disabled',
  },
]

export const mockInquiries: Inquiry[] = [
  {
    id: 'INQ-2024-891',
    customer_name: 'Sunita Verma',
    initials: 'SV',
    phone: '+91 98102 34567',
    email: 'sunita.verma@vermaholdings.com',
    location: 'Vasant Vihar, New Delhi',
    origin_channel: 'Direct Form',
    package_name: 'Kashmir Autumn Magic',
    package_id: 'pkg-kashmir-autumn',
    duration: '7 Days / 6 Nights',
    requested_dates: '18 Oct 2026 - 25 Oct 2026',
    party_size: 2,
    budget_range: '₹2,50,000 - ₹3,00,000',
    budget_min: 250000,
    budget_max: 300000,
    special_requests: 'Private Shikara kahwa ceremony at sunset, Sukoon Luxury Houseboat Presidential Suite',
    dietary_requirements: 'Strict Jain vegetarian, zero onion/garlic, organic dry fruits on charter',
    created_at: '2026-10-04T17:15:00Z',
    time_received_str: '26h ago',
    is_overdue: true,
    last_contacted_at: '2026-10-04T18:00:00Z',
    contact_attempts: 1,
    assigned_concierge: {
      id: 'unassigned',
      name: 'Unassigned',
      role: 'Action Required',
      last_activity: 'None',
    },
    status: 'New',
    priority: 'Urgent',
    conversation_log: [
      {
        id: 'msg-1',
        sender: 'System',
        senderRole: 'Website Gateway',
        timestamp: '2026-10-04 17:15 IST',
        channel: 'Direct Form',
        content: 'Bespoke inquiry received via VIP Concierge Portal (Source: Campaign HNW Delhi).',
      },
      {
        id: 'msg-2',
        sender: 'SLA Engine',
        senderRole: 'Automation',
        timestamp: '2026-10-05 17:15 IST',
        channel: 'Internal Note',
        content: '⚠️ SLA Breach: Inquiry untouched >24h. Escalated to Super Admin Devendra Rao.',
      },
    ],
  },
  {
    id: 'INQ-2024-892',
    customer_name: 'Vikramaditya Singhania',
    initials: 'VS',
    phone: '+91 98200 88910',
    email: 'vikram.singhania@singhania-group.in',
    location: 'Malabar Hill, Mumbai',
    origin_channel: 'WhatsApp',
    package_name: 'Rajasthan Royal Desert Palace',
    package_id: 'pkg-rajasthan-royal',
    duration: '6 Days / 5 Nights',
    requested_dates: '02 Nov 2026 - 08 Nov 2026',
    party_size: 4,
    budget_range: '₹4,50,000 - ₹5,50,000',
    budget_min: 450000,
    budget_max: 550000,
    special_requests: 'Private chartered dune dinner at Mihir Garh, Royal vintage car convoy escort from Jodhpur airport',
    dietary_requirements: 'Gluten-free royal Rajasthani banquet, premium champagne cellar selection',
    created_at: '2026-10-05T08:30:00Z',
    time_received_str: '11h ago',
    is_overdue: false,
    last_contacted_at: '2026-10-05T09:12:00Z',
    contact_attempts: 2,
    assigned_concierge: {
      id: 'staff-04',
      name: 'Priya Sharma',
      role: 'Lead Concierge',
      last_activity: '15m ago',
    },
    status: 'Quote Sent',
    priority: 'High',
    conversation_log: [
      {
        id: 'msg-201',
        sender: 'WhatsApp Cloud Bot',
        senderRole: 'Meta Business API',
        timestamp: '2026-10-05 08:30 IST',
        channel: 'WhatsApp',
        content: 'Guest initiated WhatsApp conversation requesting royal heritage charter in Rajasthan.',
      },
      {
        id: 'msg-202',
        sender: 'Priya Sharma',
        senderRole: 'Lead Concierge',
        timestamp: '2026-10-05 09:12 IST',
        channel: 'WhatsApp',
        content: 'Dispatched custom itinerary folio: Mihir Garh + Umaid Bhawan Palace Royal Suite with private jet feeder.',
      },
    ],
  },
  {
    id: 'INQ-2024-893',
    customer_name: 'Dr. Aisha Mukherjee',
    initials: 'AM',
    phone: '+91 98300 12940',
    email: 'aisha.mukherjee@fortis-neuro.org',
    location: 'Ballygunge, Kolkata',
    origin_channel: 'Direct Form',
    package_name: 'Kerala Backwaters Private Houseboat',
    package_id: 'pkg-kerala-houseboat',
    duration: '5 Days / 4 Nights',
    requested_dates: '12 Nov 2026 - 17 Nov 2026',
    party_size: 2,
    budget_range: '₹1,80,000 - ₹2,20,000',
    budget_min: 180000,
    budget_max: 220000,
    special_requests: 'Private solar-powered ultra-luxury cruiser, Master Ayurvedic physician consultation on board',
    dietary_requirements: 'Custom satvic & tridosha balanced gourmet wellness meals',
    created_at: '2026-10-05T14:10:00Z',
    time_received_str: '5h ago',
    is_overdue: false,
    last_contacted_at: '2026-10-05T14:45:00Z',
    contact_attempts: 1,
    assigned_concierge: {
      id: 'staff-06',
      name: 'Ananya Nambiar',
      role: 'Lead Concierge',
      last_activity: '1h ago',
    },
    status: 'Contacted',
    priority: 'Normal',
    conversation_log: [
      {
        id: 'msg-301',
        sender: 'Ananya Nambiar',
        senderRole: 'Lead Concierge',
        timestamp: '2026-10-05 14:45 IST',
        channel: 'Phone Call',
        content: 'Spoke with Dr. Mukherjee for 22 mins. Verified wellness preferences and agreed on Spice Coast ultra cruiser.',
      },
    ],
  },
  {
    id: 'INQ-2024-894',
    customer_name: 'Rajesh Mehra',
    initials: 'RM',
    phone: '+91 99100 44221',
    email: 'rajesh.mehra@jaquar-exec.com',
    location: 'Golf Links, New Delhi',
    origin_channel: 'WhatsApp',
    package_name: 'Andaman Private Island Charter',
    package_id: 'pkg-andaman-charter',
    duration: '6 Days / 5 Nights',
    requested_dates: '24 Nov 2026 - 30 Nov 2026',
    party_size: 6,
    budget_range: '₹6,00,000 - ₹7,50,000',
    budget_min: 600000,
    budget_max: 750000,
    special_requests: 'Exclusive catamaran charter to Havelock & Neil, private seaplane transfers from Port Blair',
    dietary_requirements: 'Fresh catch grilled lobster & pescatarian selection, organic cold press juices',
    created_at: '2026-10-05T11:20:00Z',
    time_received_str: '8h ago',
    is_overdue: false,
    last_contacted_at: '2026-10-05T12:00:00Z',
    contact_attempts: 3,
    assigned_concierge: {
      id: 'staff-07',
      name: 'Kabir Fernandes',
      role: 'Lead Concierge',
      last_activity: '35m ago',
    },
    status: 'Converted',
    priority: 'High',
    conversation_log: [
      {
        id: 'msg-401',
        sender: 'Kabir Fernandes',
        senderRole: 'Lead Concierge',
        timestamp: '2026-10-05 12:00 IST',
        channel: 'WhatsApp',
        content: 'Dispatched custom catamaran quote. Client confirmed charter and accepted Tranche 1 payment terms.',
      },
    ],
  },
  {
    id: 'INQ-2024-895',
    customer_name: 'Gayatri Oberoi',
    initials: 'GO',
    phone: '+91 98210 99441',
    email: 'gayatri.oberoi@oberoifamily.in',
    location: 'Cuffe Parade, Mumbai',
    origin_channel: 'Direct Form',
    package_name: 'Rajasthan Royal Desert Palace',
    package_id: 'pkg-rajasthan-royal',
    duration: '5 Days / 4 Nights',
    requested_dates: '14 Nov 2026 - 19 Nov 2026',
    party_size: 2,
    budget_range: '₹3,00,000 - ₹3,80,000',
    budget_min: 300000,
    budget_max: 380000,
    special_requests: 'Private sunset sitar recital at Lake Palace Udaipur, vintage boat transfer',
    dietary_requirements: 'Low sodium, plant-based luxury gourmet menu',
    created_at: '2026-10-04T18:40:00Z',
    time_received_str: '25h ago',
    is_overdue: true,
    last_contacted_at: 'None',
    contact_attempts: 0,
    assigned_concierge: {
      id: 'unassigned',
      name: 'Unassigned',
      role: 'Action Required',
      last_activity: 'None',
    },
    status: 'New',
    priority: 'Urgent',
    conversation_log: [
      {
        id: 'msg-501',
        sender: 'System',
        senderRole: 'Website Gateway',
        timestamp: '2026-10-04 18:40 IST',
        channel: 'Direct Form',
        content: 'Inquiry received. Awaiting round-robin lead allocation.',
      },
    ],
  },
  {
    id: 'INQ-2024-896',
    customer_name: 'Arjun Singhal',
    initials: 'AS',
    phone: '+91 98188 55412',
    email: 'arjun.singhal@singhal-metals.com',
    location: 'Civil Lines, Jaipur',
    origin_channel: 'Direct Form',
    package_name: 'Leh Ladakh High Altitude Luxury',
    package_id: 'pkg-ladakh-luxury',
    duration: '8 Days / 7 Nights',
    requested_dates: '01 Nov 2026 - 09 Nov 2026',
    party_size: 4,
    budget_range: '₹5,00,000 - ₹6,20,000',
    budget_min: 500000,
    budget_max: 620000,
    special_requests: 'Oxygen-fitted luxury glamping suites at Nubra & Pangong, private helicopter sortie',
    dietary_requirements: 'High protein energy cuisine, organic herbal soups',
    created_at: '2026-10-04T19:20:00Z',
    time_received_str: '24h ago',
    is_overdue: true,
    last_contacted_at: 'None',
    contact_attempts: 0,
    assigned_concierge: {
      id: 'unassigned',
      name: 'Unassigned',
      role: 'Action Required',
      last_activity: 'None',
    },
    status: 'New',
    priority: 'Urgent',
    conversation_log: [
      {
        id: 'msg-601',
        sender: 'System',
        senderRole: 'Website Gateway',
        timestamp: '2026-10-04 19:20 IST',
        channel: 'Direct Form',
        content: 'Lead captured from High-Net-Worth Ladakh Campaign. Unassigned > 24 hours.',
      },
    ],
  },
]

export const mockBookings: Booking[] = [
  {
    id: '#AV-2024-118',
    customer_id: 'cust-01',
    customer_name: 'Sanjay Singhania',
    customer_phone: '+91 98200 88910',
    customer_email: 'sanjay@singhaniagroup.in',
    guest_initials: 'SS',
    package_name: 'Kashmir Autumn Magic',
    package_id: 'pkg-kashmir-autumn',
    package_duration: '7 Days / 6 Nights',
    departure_date: '2026-10-07',
    return_date: '2026-10-14',
    departure_time: '10:30 AM IST (Private Jet Feeder)',
    party_size: '2 Adults (Presidential)',
    party_count: 2,
    total_amount: 185000,
    paid_amount: 92500,
    payment_status: 'Failed',
    chauffeur: {
      assigned: true,
      name: 'Bashir Ahmad Wani',
      phone: '+91 94190 77112',
      vehicle: 'Mercedes V-Class Maybach Edition',
      license_plate: 'JK-01-AB-9901',
    },
    voucher: {
      generated: true,
      sent: false,
      pdf_url: '/vouchers/AV-2024-118.pdf',
      due_urgent: true,
      status: 'Ready',
    },
    status: 'Pending',
    guests: [
      { name: 'Sanjay Singhania', age: 48, relation: 'Lead Passenger', passport_verified: true, id_number_masked: 'P892••••K' },
      { name: 'Meera Singhania', age: 45, relation: 'Spouse', passport_verified: true, id_number_masked: 'P893••••M' },
    ],
    blueprint: {
      itinerary_highlights: [
        'Private jet touchdown at Srinagar Military Enclave with VIP tarmac escort',
        '3 Nights Presidential Suite Sukoon Luxury Houseboat on Lake Nigeen',
        '2 Nights The Khyber Himalayan Resort Gulmarg with heated outdoor hydrotherapy',
        'Private saffron picking & saffron kahwa ceremony in Pampore',
      ],
      inclusions: [
        'Mercedes V-Class with English/Urdu speaking executive chauffeur',
        '24/7 dedicated lead concierge Tariq Ahmad Mir on site',
        'All private shikara crossings and royal banquet meals',
      ],
      special_requests: 'HDFC Bank transaction failed due to OTP gateway timeout. Tranche 2 pending.',
    },
    notes: [
      { timestamp: '05 Oct 2026 14:22', author: 'Razorpay Webhook', text: 'Payment attempt for Tranche 2 failed: Bank timeout' },
      { timestamp: '05 Oct 2026 14:25', author: 'Tariq Ahmad', text: 'Dispatched 1-click WhatsApp retry link to Sanjay Singhania.' },
    ],
  },
  {
    id: '#AV-2024-112',
    customer_id: 'cust-02',
    customer_name: 'Anand Mahindra Charter',
    customer_phone: '+91 98110 33410',
    customer_email: 'charters@mahindra-office.in',
    guest_initials: 'AM',
    package_name: 'Leh Ladakh High Altitude Luxury',
    package_id: 'pkg-ladakh-luxury',
    package_duration: '8 Days / 7 Nights',
    departure_date: '2026-10-07',
    return_date: '2026-10-15',
    departure_time: '07:15 AM IST (Charter ATR-42)',
    party_size: '4 Guests (Executive)',
    party_count: 4,
    total_amount: 380000,
    paid_amount: 380000,
    payment_status: 'Captured',
    chauffeur: {
      assigned: true,
      name: 'Stanzin Dorje',
      phone: '+91 94191 00293',
      vehicle: 'Toyota Land Cruiser Prado VIP',
      license_plate: 'LA-02-C-4400',
    },
    voucher: {
      generated: false,
      sent: false,
      pdf_url: '',
      due_urgent: true,
      status: 'Pending',
    },
    status: 'Confirmed',
    guests: [
      { name: 'Kavita Anand', age: 52, relation: 'Lead Guest', passport_verified: true, id_number_masked: 'Z102••••D' },
      { name: 'Rohan Anand', age: 24, relation: 'Guest', passport_verified: true, id_number_masked: 'Z103••••F' },
      { name: 'Vikram Sethi', age: 54, relation: 'Guest', passport_verified: true, id_number_masked: 'Z104••••G' },
      { name: 'Tara Sethi', age: 50, relation: 'Guest', passport_verified: true, id_number_masked: 'Z105••••H' },
    ],
    blueprint: {
      itinerary_highlights: [
        'Arrival Leh, complete acclimatisation day at The Grand Dragon Royal Suite',
        'Private monastery chanting session at Thiksey with head lama',
        'Helicopter charter over Khardung La directly to Chamba Camp Thiksey',
      ],
      inclusions: ['Medical oxygen team escort', 'Private butler', 'All charter permits'],
      special_requests: 'Voucher awaiting final itinerary sign-off from Devendra Rao.',
    },
    notes: [
      { timestamp: '05 Oct 2026 11:00', author: 'Devendra Rao', text: 'Air force clearance received for civilian charter.' },
    ],
  },
  {
    id: '#AV-2024-114',
    customer_id: 'cust-03',
    customer_name: 'Radhika Goenka',
    customer_phone: '+91 98212 99401',
    customer_email: 'radhika.goenka@rpg-enterprises.com',
    guest_initials: 'RG',
    package_name: 'Kerala Backwaters Private Houseboat',
    package_id: 'pkg-kerala-houseboat',
    package_duration: '5 Days / 4 Nights',
    departure_date: '2026-10-07',
    return_date: '2026-10-12',
    departure_time: '11:00 AM IST (Kochi VIP Terminal)',
    party_size: '2 Adults (Heritage)',
    party_count: 2,
    total_amount: 145000,
    paid_amount: 145000,
    payment_status: 'Captured',
    chauffeur: {
      assigned: true,
      name: 'Mathen Varghese',
      phone: '+91 98471 22891',
      vehicle: 'Toyota Alphard Executive Lounge',
      license_plate: 'KL-07-CD-1122',
    },
    voucher: {
      generated: false,
      sent: false,
      pdf_url: '',
      due_urgent: true,
      status: 'Pending',
    },
    status: 'Confirmed',
    guests: [
      { name: 'Radhika Goenka', age: 36, relation: 'Lead', passport_verified: true, id_number_masked: 'T992••••A' },
      { name: 'Aarav Poddar', age: 38, relation: 'Partner', passport_verified: true, id_number_masked: 'T993••••B' },
    ],
    blueprint: {
      itinerary_highlights: [
        'Private solar cruise departing Alleppey towards Kumarakom private sanctuary',
        'Chef George craft seafood tasting menu and sunset Kathakali performance',
      ],
      inclusions: ['Private crew of 4 on boat', 'Ayurvedic masseuse on call'],
      special_requests: 'Awaiting voucher dispatch before 48h departure cutoff.',
    },
    notes: [
      { timestamp: '04 Oct 2026 16:30', author: 'Ananya Nambiar', text: 'Houseboat sanitized and private jetty secured.' },
    ],
  },
  {
    id: '#AV-2024-115',
    customer_id: 'cust-04',
    customer_name: 'Sunita Verma',
    customer_phone: '+91 98102 34567',
    customer_email: 'sunita.verma@vermaholdings.com',
    guest_initials: 'SV',
    package_name: 'Rajasthan Royal Desert Palace',
    package_id: 'pkg-rajasthan-royal',
    package_duration: '6 Days / 5 Nights',
    departure_date: '2026-10-10',
    return_date: '2026-10-16',
    departure_time: '09:00 AM IST',
    party_size: '4 Guests',
    party_count: 4,
    total_amount: 275000,
    paid_amount: 275000,
    payment_status: 'Captured',
    chauffeur: {
      assigned: true,
      name: 'Gajendra Singh',
      phone: '+91 98290 88123',
      vehicle: 'Mercedes V-Class Exclusive',
      license_plate: 'RJ-14-EA-7788',
    },
    voucher: {
      generated: true,
      sent: true,
      pdf_url: '/vouchers/AV-2024-115.pdf',
      due_urgent: false,
      status: 'Ready',
    },
    status: 'Confirmed',
    guests: [
      { name: 'Sunita Verma', age: 46, relation: 'Lead Guest', passport_verified: true, id_number_masked: 'M331••••R' },
      { name: 'Ashok Verma', age: 50, relation: 'Spouse', passport_verified: true, id_number_masked: 'M332••••S' },
      { name: 'Kunal Verma', age: 19, relation: 'Son', passport_verified: true, id_number_masked: 'M333••••T' },
      { name: 'Ananya Verma', age: 16, relation: 'Daughter', passport_verified: true, id_number_masked: 'M334••••U' },
    ],
    blueprint: {
      itinerary_highlights: [
        'Udaipur Lake Palace Grand Heritage Suite',
        'Private sunset boat to Jagmandir with royal sitar concert',
        'Helicopter transit to Suján The Serai Jaisalmer for luxury tented desert stay',
      ],
      inclusions: ['All royal monument VIP permits', 'Private historian guide', 'Private chef'],
      special_requests: 'Strict vegetarian dining verified.',
    },
    notes: [
      { timestamp: '03 Oct 2026 12:15', author: 'Priya Sharma', text: 'Voucher dispatched via WhatsApp to Sunita Verma.' },
    ],
  },
  {
    id: '#AV-2024-116',
    customer_id: 'cust-05',
    customer_name: 'Rajesh Mehra',
    customer_phone: '+91 99100 44221',
    customer_email: 'rajesh.mehra@jaquar-exec.com',
    guest_initials: 'RM',
    package_name: 'Andaman Private Island Charter',
    package_id: 'pkg-andaman-charter',
    package_duration: '6 Days / 5 Nights',
    departure_date: '2026-10-18',
    return_date: '2026-10-24',
    departure_time: '12:45 PM IST',
    party_size: '6 Guests',
    party_count: 6,
    total_amount: 450000,
    paid_amount: 225000,
    payment_status: 'Captured',
    chauffeur: {
      assigned: false,
      name: 'Unassigned',
      phone: '',
      vehicle: 'Private Yacht + Land Cruiser',
      license_plate: '',
    },
    voucher: {
      generated: false,
      sent: false,
      pdf_url: '',
      due_urgent: false,
      status: 'Pending',
    },
    status: 'Confirmed',
    guests: [
      { name: 'Rajesh Mehra', age: 54, relation: 'Lead', passport_verified: true, id_number_masked: 'P112••••Q' },
      { name: 'Sunaina Mehra', age: 51, relation: 'Spouse', passport_verified: true, id_number_masked: 'P113••••W' },
    ],
    blueprint: {
      itinerary_highlights: [
        'Private 52ft Leopard Catamaran cruising between Havelock and Barren Island',
        'PADI master diver private lessons for the family',
      ],
      inclusions: ['All island marine sanctuary permits', 'Chef and crew of 3'],
      special_requests: 'Tranche 2 balance due in 5 days.',
    },
    notes: [
      { timestamp: '02 Oct 2026 18:00', author: 'Kabir Fernandes', text: 'Catamaran reserved with Andaman Fleet Captain.' },
    ],
  },
]

export const mockPayments: Payment[] = [
  {
    id: 'pay_On82kd82mQ',
    booking_id: '#AV-2024-118',
    expedition: 'Kashmir Autumn Magic',
    customer_name: 'Sanjay Singhania',
    customer_phone: '+91 98200 88910',
    customer_email: 'sanjay@singhaniagroup.in',
    amount: 185000,
    tranche_info: 'Tranche 1 of 2 (Deposit)',
    currency: 'INR',
    gateway_status: 'Captured',
    payment_method: 'UPI',
    timestamp: 'Today, 14:22 IST',
    razorpay_id: 'pay_On82kd82mQ',
    retry_link_sent: false,
  },
  {
    id: 'pay_Rz91ld99vX',
    booking_id: '#AV-2024-118',
    expedition: 'Kashmir Autumn Magic',
    customer_name: 'Sanjay Singhania',
    customer_phone: '+91 98200 88910',
    customer_email: 'sanjay@singhaniagroup.in',
    amount: 92500,
    tranche_info: 'Tranche 2 of 2 (Balance Due)',
    currency: 'INR',
    gateway_status: 'Failed',
    payment_method: 'Netbanking',
    timestamp: 'Today, 14:24 IST',
    razorpay_id: 'pay_Rz91ld99vX',
    retry_link_sent: true,
    failed_reason: 'Bank timeout (HDFC Netbanking 504 Gateway Timeout). 1-Click WhatsApp retry link dispatched.',
  },
  {
    id: 'pay_Lk11po44kM',
    booking_id: '#AV-2024-112',
    expedition: 'Leh Ladakh High Altitude Luxury',
    customer_name: 'Anand Mahindra Charter',
    customer_phone: '+91 98110 33410',
    customer_email: 'charters@mahindra-office.in',
    amount: 380000,
    tranche_info: 'Full 100% Escrow Advance',
    currency: 'INR',
    gateway_status: 'Captured',
    payment_method: 'Amex',
    timestamp: 'Today, 11:05 IST',
    razorpay_id: 'pay_Lk11po44kM',
  },
  {
    id: 'pay_Xp77mn12qR',
    booking_id: '#AV-2024-114',
    expedition: 'Kerala Backwaters Private Houseboat',
    customer_name: 'Radhika Goenka',
    customer_phone: '+91 98212 99401',
    customer_email: 'radhika.goenka@rpg-enterprises.com',
    amount: 145000,
    tranche_info: 'Full Advance Payment',
    currency: 'INR',
    gateway_status: 'Captured',
    payment_method: 'UPI',
    timestamp: 'Yesterday, 17:40 IST',
    razorpay_id: 'pay_Xp77mn12qR',
  },
  {
    id: 'pay_Qa55vb88wT',
    booking_id: '#AV-2024-115',
    expedition: 'Rajasthan Royal Desert Palace',
    customer_name: 'Sunita Verma',
    customer_phone: '+91 98102 34567',
    customer_email: 'sunita.verma@vermaholdings.com',
    amount: 275000,
    tranche_info: 'Full Advance Payment',
    currency: 'INR',
    gateway_status: 'Captured',
    payment_method: 'Credit Card',
    timestamp: '03 Oct 2026, 12:00 IST',
    razorpay_id: 'pay_Qa55vb88wT',
  },
  {
    id: 'pay_Zz33rt44yU',
    booking_id: '#AV-2024-098',
    expedition: 'Kashmir Autumn Magic',
    customer_name: 'Vikram Godrej',
    customer_phone: '+91 98201 00293',
    customer_email: 'vikram.g@godrej-invest.in',
    amount: 185000,
    tranche_info: 'Tranche 1 Refund Clawback',
    currency: 'INR',
    gateway_status: 'Refunded',
    payment_method: 'UPI',
    timestamp: '02 Oct 2026, 15:30 IST',
    razorpay_id: 'pay_Zz33rt44yU',
    refund_details: {
      original_amount: 185000,
      deduction_amount: 25000,
      deduction_reason: 'Charter cancellation levy (policy schedule 4B)',
      net_payout: 160000,
      reason: 'Customer Requested (Medical Emergency in Family)',
      audit_note: 'Verified with Max Healthcare medical certificate by Meenakshi Sundaram.',
      credit_note_id: 'CN-AV-2024-041',
      disbursement_method: 'NPCI UPI Clawback (45s settlement)',
      disbursed_at: '02 Oct 2026, 15:31 IST',
    },
  },
  {
    id: 'pay_Mm44pp88oP',
    booking_id: '#AV-2024-116',
    expedition: 'Andaman Private Island Charter',
    customer_name: 'Rajesh Mehra',
    customer_phone: '+91 99100 44221',
    customer_email: 'rajesh.mehra@jaquar-exec.com',
    amount: 225000,
    tranche_info: 'Tranche 1 of 2 (Deposit)',
    currency: 'INR',
    gateway_status: 'Captured',
    payment_method: 'Axis Bank',
    timestamp: '01 Oct 2026, 16:15 IST',
    razorpay_id: 'pay_Mm44pp88oP',
  },
  {
    id: 'pay_Kk99jj11qA',
    booking_id: '#AV-2024-105',
    expedition: 'Leh Ladakh High Altitude Luxury',
    customer_name: 'Ananya Birla Trust',
    customer_phone: '+91 98210 11982',
    customer_email: 'trust.ops@birla.org',
    amount: 75000,
    tranche_info: 'Cancellation Adjustment',
    currency: 'INR',
    gateway_status: 'Refunded',
    payment_method: 'Netbanking',
    timestamp: '29 Sep 2026, 10:20 IST',
    razorpay_id: 'pay_Kk99jj11qA',
    refund_details: {
      original_amount: 75000,
      deduction_amount: 0,
      deduction_reason: 'Aariva weather closure waiver',
      net_payout: 75000,
      reason: 'Aariva Cancellation (Pass snow block)',
      audit_note: 'Approved by Devendra Rao. 100% waiver issued.',
      credit_note_id: 'CN-AV-2024-039',
      disbursement_method: 'NEFT Direct Gateway Return',
      disbursed_at: '29 Sep 2026, 10:22 IST',
    },
  },
]

export const mockCustomers: Customer[] = [
  {
    id: 'cust-01',
    name: 'Sunita Verma',
    initials: 'SV',
    email: 'sunita.verma@vermaholdings.com',
    phone: '+91 98102 34567',
    whatsapp: '+91 98102 34567',
    upi_id: 'vermasunita@okhdfcbank',
    location: 'Vasant Vihar, New Delhi',
    tier: 'Elite Sovereign',
    tier_badge: 'SOVEREIGN VIP',
    lifetime_spend: 785000,
    expedition_count: 4,
    trips_summary: '4 Trips (3 Done • 1 Enroute)',
    completed_trips: 3,
    enroute_trips: 1,
    repeat_intent_score: 'High (98.2%)',
    nps_score: '10 / 10',
    status: 'Active',
    last_activity: 'Today, 1h ago',
    relationship_manager: {
      name: 'Devendra Rao',
      role: 'Super Admin & Lead Concierge',
    },
    co_travellers: [
      { name: 'Ashok Verma', relation: 'Spouse', passport_verified: true },
      { name: 'Kunal Verma', relation: 'Son', passport_verified: true },
      { name: 'Ananya Verma', relation: 'Daughter', passport_verified: true },
    ],
    bespoke_preferences: {
      dietary: 'Strict Vegetarian (main meal prep on private flights & houseboats, zero onion/garlic)',
      accommodations: 'Luxury houseboats, heritage suites, quiet non-smoking rooms on highest floor',
      chauffeur: 'Mercedes V-Class or Toyota Alphard, English/Hindi speaking, vetted security clearance',
      passport_verified: true,
      special_notes: 'Prefers morning kahwa ceremony served with raw almonds and organic saffron.',
    },
    expedition_history: [
      {
        order_id: '#AV-2024-115',
        expedition_name: 'Rajasthan Royal Desert Palace',
        dates: '10 Oct 2026 - 16 Oct 2026',
        accommodation: 'Lake Palace Udaipur & Mihir Garh',
        amount: 275000,
        status: 'Confirmed',
      },
      {
        order_id: '#AV-2024-042',
        expedition_name: 'Kashmir Autumn Magic',
        dates: '14 Oct 2025 - 20 Oct 2025',
        accommodation: 'Sukoon Luxury Houseboat & The Khyber Gulmarg',
        amount: 210000,
        status: 'Completed',
      },
      {
        order_id: '#AV-2024-018',
        expedition_name: 'Kerala Backwaters Private Houseboat',
        dates: '02 Feb 2025 - 07 Feb 2025',
        accommodation: 'Spice Coast Luxury Cruiser',
        amount: 160000,
        status: 'Completed',
      },
      {
        order_id: '#AV-2023-089',
        expedition_name: 'Andaman Private Island Charter',
        dates: '20 Nov 2023 - 26 Nov 2023',
        accommodation: 'Taj Exotica Resort & Private Yacht',
        amount: 140000,
        status: 'Completed',
      },
    ],
    internal_notes: [
      {
        timestamp: '24 Oct 2024, 11:30 AM',
        author: 'Devendra Rao',
        text: 'Requested fresh Kashmiri kahwa ceremony arranged for 4 persons upon arrival at Srinagar airport.',
      },
      {
        timestamp: '15 Sep 2026, 16:45 PM',
        author: 'Priya Sharma',
        text: 'Client requested Mercedes V-Class Maybach spec for Rajasthan leg. Chauffeur Gajendra Singh re-assigned.',
      },
    ],
  },
  {
    id: 'cust-02',
    name: 'Sanjay Singhania',
    initials: 'SS',
    email: 'sanjay@singhaniagroup.in',
    phone: '+91 98200 88910',
    whatsapp: '+91 98200 88910',
    upi_id: 'singhanias@icici',
    location: 'Malabar Hill, Mumbai',
    tier: 'Elite Sovereign',
    tier_badge: 'SOVEREIGN VIP',
    lifetime_spend: 1240000,
    expedition_count: 5,
    trips_summary: '5 Trips (4 Done • 1 Enroute)',
    completed_trips: 4,
    enroute_trips: 1,
    repeat_intent_score: 'Very High (99.0%)',
    nps_score: '10 / 10',
    status: 'Active',
    last_activity: '14m ago',
    relationship_manager: {
      name: 'Tariq Ahmad Mir',
      role: 'Lead Concierge Kashmir',
    },
    co_travellers: [{ name: 'Meera Singhania', relation: 'Spouse', passport_verified: true }],
    bespoke_preferences: {
      dietary: 'Continental & Mediterranean, sparkling mineral water, cold brew bar on board',
      accommodations: 'Presidential Suites only, private lake moorings',
      chauffeur: 'Mercedes V-Class or S-Class',
      passport_verified: true,
      special_notes: 'Private aviation tarmac clearance mandatory.',
    },
    expedition_history: [
      {
        order_id: '#AV-2024-118',
        expedition_name: 'Kashmir Autumn Magic',
        dates: '07 Oct 2026 - 14 Oct 2026',
        accommodation: 'Sukoon Houseboat & Khyber',
        amount: 185000,
        status: 'Enroute',
      },
    ],
    internal_notes: [
      { timestamp: '05 Oct 2026, 14:26', author: 'Tariq Ahmad', text: 'Handled failed payment notification with private assistant.' },
    ],
  },
  {
    id: 'cust-03',
    name: 'Radhika Goenka',
    initials: 'RG',
    email: 'radhika.goenka@rpg-enterprises.com',
    phone: '+91 98212 99401',
    whatsapp: '+91 98212 99401',
    upi_id: 'radhikagoenka@axisbank',
    location: 'Worli Seaface, Mumbai',
    tier: 'VIP Club',
    tier_badge: 'AZURE VOYAGER',
    lifetime_spend: 520000,
    expedition_count: 3,
    trips_summary: '3 Trips (2 Done • 1 Enroute)',
    completed_trips: 2,
    enroute_trips: 1,
    repeat_intent_score: 'High (95.0%)',
    nps_score: '9 / 10',
    status: 'Active',
    last_activity: 'Yesterday',
    relationship_manager: {
      name: 'Ananya Nambiar',
      role: 'Lead Concierge Kerala',
    },
    co_travellers: [{ name: 'Aarav Poddar', relation: 'Partner', passport_verified: true }],
    bespoke_preferences: {
      dietary: 'Organic vegan, gluten-free, ayurvedic herbal infusions',
      accommodations: 'Eco-luxury sanctuaries, private plunge pool',
      chauffeur: 'Toyota Alphard Executive Lounge',
      passport_verified: true,
      special_notes: 'Prefers quiet sunrise departures.',
    },
    expedition_history: [
      {
        order_id: '#AV-2024-114',
        expedition_name: 'Kerala Backwaters Private Houseboat',
        dates: '07 Oct 2026 - 12 Oct 2026',
        accommodation: 'Spice Coast Cruiser',
        amount: 145000,
        status: 'Confirmed',
      },
    ],
    internal_notes: [
      { timestamp: '04 Oct 2026, 11:00', author: 'Ananya Nambiar', text: 'Private yoga instructor arranged on houseboat deck.' },
    ],
  },
  {
    id: 'cust-04',
    name: 'Rajesh Mehra',
    initials: 'RM',
    email: 'rajesh.mehra@jaquar-exec.com',
    phone: '+91 99100 44221',
    whatsapp: '+91 99100 44221',
    upi_id: 'mehra.rajesh@okaxis',
    location: 'Golf Links, New Delhi',
    tier: 'Frequent Voyager',
    tier_badge: 'AZURE VOYAGER',
    lifetime_spend: 675000,
    expedition_count: 3,
    trips_summary: '3 Trips (2 Done • 1 Enroute)',
    completed_trips: 2,
    enroute_trips: 1,
    repeat_intent_score: '96.4%',
    nps_score: '10 / 10',
    status: 'Active',
    last_activity: '12 days ago',
    relationship_manager: {
      name: 'Kabir Fernandes',
      role: 'Lead Concierge Andaman',
    },
    co_travellers: [{ name: 'Sunaina Mehra', relation: 'Spouse', passport_verified: true }],
    bespoke_preferences: {
      dietary: 'Pescatarian seafood & Asian fusion',
      accommodations: 'Overwater bungalows and island villas',
      chauffeur: 'Toyota Prado or Mercedes V-Class',
      passport_verified: true,
      special_notes: 'PADI Master Diver certified.',
    },
    expedition_history: [
      {
        order_id: '#AV-2024-116',
        expedition_name: 'Andaman Private Island Charter',
        dates: '18 Oct 2026 - 24 Oct 2026',
        accommodation: 'Private Catamaran Charter',
        amount: 450000,
        status: 'Confirmed',
      },
    ],
    internal_notes: [
      { timestamp: '22 Sep 2026, 14:00', author: 'Kabir Fernandes', text: 'Confirmed private dive master for Barren Island sortie.' },
    ],
  },
]

export const mockReviews: Review[] = [
  {
    id: 'rev-pending-01',
    booking_id: '#AV-2024-042',
    guest_name: 'Sunita Verma',
    guest_initials: 'SV',
    tier: 'SOVEREIGN CLUB',
    expedition: 'Kashmir Autumn Magic',
    dates: '14 Oct 2025 - 20 Oct 2025',
    rating: 5,
    submitted_time: '2h ago',
    review_quote: 'Unmatched hospitality and breathtaking Dal Lake serenity. The private shikara kahwa ceremony was unforgettable.',
    review_text:
      'Aariva Voyages exceeded every possible expectation. Devendra and Tariq curated a truly magical expedition. The Sukoon Houseboat was pristine, and having our private chef cater strictly to our Jain dietary needs without a single flaw made us feel like royalty. The helicopter transfer to Gulmarg was seamless. Truly the pinnacle of Indian luxury travel.',
    photos: [
      { url: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80', caption: 'Shikara sunset on Nigeen Lake', exif_verified: true, raw_verified: true },
      { url: 'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=800&q=80', caption: 'Private Kahwa ceremony in Gulmarg', exif_verified: true, raw_verified: true },
      { url: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80', caption: 'Autumn Chinar trees in Srinagar', exif_verified: true, raw_verified: true },
    ],
    safety_sentiment: 'PASSED',
    photo_checks: 'VERIFIED (3 RAW)',
    guest_authentication: 'MATCHED (PNR-770)',
    auto_moderation: 'Clean',
    status: 'Pending',
    syndicate_targets: ['Homepage Carousel', 'Destination Hero Page', 'Print Lookbook', 'Winter 2024 Luxury Catalogue'],
    official_reply: {
      author: 'Devendra Rao (Ops Lead)',
      timestamp: 'Drafted 30m ago',
      text: 'Dear Sunita, We are profoundly honoured to have crafted this journey for your family. The warmth of the Kashmir valley combined with the timeless elegance of Sukoon Houseboat is always unforgettable. We look forward to hosting you for your upcoming Rajasthan royal voyage.',
    },
  },
  {
    id: 'rev-pending-02',
    booking_id: '#AV-2024-039',
    guest_name: 'Aaditya Singhania',
    guest_initials: 'AS',
    tier: 'SOVEREIGN CLUB',
    expedition: 'Rajasthan Royal Desert Palace',
    dates: '28 Sep 2026 - 03 Oct 2026',
    rating: 5,
    submitted_time: '5h ago',
    review_quote: 'The private dune dinner at Mihir Garh was transcendental. Flawless concierge handling throughout.',
    review_text:
      'Priya Sharma and her team coordinated our vintage convoy from Jodhpur with military precision. Our stay at the Umaid Bhawan Palace Maharaja Suite was unforgettable, and the royal sitar ensemble during the candlelit dinner in the dunes will be cherished forever.',
    photos: [
      { url: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80', caption: 'Private candlelit dinner at Mihir Garh', exif_verified: true, raw_verified: true },
      { url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80', caption: 'Vintage car arrival at Jodhpur', exif_verified: true, raw_verified: true },
    ],
    safety_sentiment: 'PASSED',
    photo_checks: 'VERIFIED (3 RAW)',
    guest_authentication: 'MATCHED (PNR-770)',
    auto_moderation: 'Clean',
    status: 'Pending',
    syndicate_targets: ['Homepage Carousel', 'Destination Hero Page'],
  },
  {
    id: 'rev-pending-03',
    booking_id: '#AV-2024-031',
    guest_name: 'Dr. Aisha Mukherjee',
    guest_initials: 'AM',
    tier: 'AZURE CLUB',
    expedition: 'Kerala Backwaters Private Houseboat',
    dates: '15 Sep 2026 - 20 Sep 2026',
    rating: 5,
    submitted_time: '18h ago',
    review_quote: 'The Ayurvedic rejuvenation aboard the solar cruiser was deeply restorative. World-class wellness curation.',
    review_text:
      'As a neurosurgeon, tranquility is rare in my daily life. The five days aboard Aariva’s private solar cruiser through the secluded canals of Kumarakom provided genuine healing. The private Ayurvedic physician and fresh satvic meals were extraordinary.',
    photos: [
      { url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80', caption: 'Backwaters sunrise from private cruiser deck', exif_verified: true, raw_verified: true },
    ],
    safety_sentiment: 'PASSED',
    photo_checks: 'VERIFIED (3 RAW)',
    guest_authentication: 'MATCHED (PNR-770)',
    auto_moderation: 'Clean',
    status: 'Pending',
    syndicate_targets: ['Homepage Carousel', 'Winter 2024 Luxury Catalogue'],
  },
  {
    id: 'rev-published-01',
    booking_id: '#AV-2024-018',
    guest_name: 'Kavita Anand',
    guest_initials: 'KA',
    tier: 'SOVEREIGN CLUB',
    expedition: 'Leh Ladakh High Altitude Luxury',
    dates: '10 Aug 2026 - 17 Aug 2026',
    rating: 5,
    submitted_time: '2 weeks ago',
    review_quote: 'Glamping under the Nubra Valley Milky Way with private oxygen concierge. Beyond sensational.',
    review_text:
      'Ladakh can be daunting at 12,000 feet, but Aariva made it effortless. The pressurized glamping suites, dedicated emergency medical escort, and private helicopter to Pangong Lake made this trip life-affirming.',
    photos: [],
    safety_sentiment: 'PASSED',
    photo_checks: 'VERIFIED (3 RAW)',
    guest_authentication: 'MATCHED (PNR-770)',
    auto_moderation: 'Clean',
    status: 'Featured',
    syndicate_targets: ['Homepage Carousel', 'Print Lookbook', 'Winter 2024 Luxury Catalogue'],
    official_reply: {
      author: 'Devendra Rao',
      timestamp: '2 weeks ago',
      text: 'Thank you Kavita. Our high-altitude expedition team works tirelessly to pair raw Himalayan grandeur with uncompromising safety and comfort.',
    },
  },
  {
    id: 'rev-published-02',
    booking_id: '#AV-2024-012',
    guest_name: 'Vikram Godrej',
    guest_initials: 'VG',
    tier: 'AZURE CLUB',
    expedition: 'Andaman Private Island Charter',
    dates: '04 Jul 2026 - 10 Jul 2026',
    rating: 5,
    submitted_time: '1 month ago',
    review_quote: 'Untouched coral reefs, private seaplane drop-offs, and 5-star yacht dining in the Bay of Bengal.',
    review_text:
      'Having chartered yachts in Monaco and the Caribbean, I was stunned by how Aariva matched that tier of service in the Andaman Islands. Kabir Fernandes anticipated every need.',
    photos: [],
    safety_sentiment: 'PASSED',
    photo_checks: 'VERIFIED (3 RAW)',
    guest_authentication: 'MATCHED (PNR-770)',
    auto_moderation: 'Clean',
    status: 'Published',
    syndicate_targets: ['Destination Hero Page'],
  },
]

export const mockDepartureRadar = [
  { day: 'Wed', date: '07 Oct', count: 3, label: '3 Exps', departures: [
    { id: '#AV-2024-118', initials: 'SS', guest: 'Sanjay Singhania', expedition: 'Kashmir Autumn Magic', voucherReady: true },
    { id: '#AV-2024-112', initials: 'AM', guest: 'Anand Mahindra Charter', expedition: 'Leh Ladakh Luxury', voucherReady: false },
    { id: '#AV-2024-114', initials: 'RG', guest: 'Radhika Goenka', expedition: 'Kerala Backwaters', voucherReady: false },
  ]},
  { day: 'Thu', date: '08 Oct', count: 1, label: '1 Exp', departures: [
    { id: '#AV-2024-119', initials: 'DO', guest: 'Deepak Parekh Group', expedition: 'Rajasthan Royal Desert', voucherReady: true },
  ]},
  { day: 'Fri', date: '09 Oct', count: 2, label: '2 Exps', departures: [
    { id: '#AV-2024-120', initials: 'VK', guest: 'Vinod Khosla Estate', expedition: 'Andaman Island Charter', voucherReady: true },
    { id: '#AV-2024-121', initials: 'NJ', guest: 'Nita Jindal', expedition: 'Kashmir Autumn Magic', voucherReady: true },
  ]},
  { day: 'Sat', date: '10 Oct', count: 2, label: '2 Exps', departures: [
    { id: '#AV-2024-115', initials: 'SV', guest: 'Sunita Verma', expedition: 'Rajasthan Royal Desert Palace', voucherReady: true },
    { id: '#AV-2024-122', initials: 'TB', guest: 'Tarun Bajaj', expedition: 'Kerala Backwaters', voucherReady: false },
  ]},
  { day: 'Sun', date: '11 Oct', count: 0, label: '0 Exps', departures: [] },
  { day: 'Mon', date: '12 Oct', count: 1, label: '1 Exp', departures: [
    { id: '#AV-2024-123', initials: 'AK', guest: 'Ashish Khemka', expedition: 'Leh Ladakh Luxury', voucherReady: true },
  ]},
  { day: 'Tue', date: '13 Oct', count: 2, label: '2 Exps', departures: [
    { id: '#AV-2024-124', initials: 'MN', guest: 'Manish Nanda', expedition: 'Kashmir Autumn Magic', voucherReady: true },
    { id: '#AV-2024-125', initials: 'RK', guest: 'Rishi Kapoor Family', expedition: 'Andaman Private Island', voucherReady: false },
  ]},
]

export const mockRevenueTrends = [
  { month: 'May', actual: 2950000, target: 2800000 },
  { month: 'Jun', actual: 3200000, target: 3000000 },
  { month: 'Jul', actual: 3120000, target: 3200000 },
  { month: 'Aug', actual: 3480000, target: 3400000 },
  { month: 'Sep', actual: 3345000, target: 3600000 },
  { month: 'Oct (MTD)', actual: 3840000, target: 4200000 },
]

export const mockTopPackages = [
  { name: 'Kashmir Autumn Magic', volume: 24, revenue: 1620000, share: '42%' },
  { name: 'Kerala Backwaters Private Houseboat', volume: 18, revenue: 1170000, share: '30%' },
  { name: 'Rajasthan Royal Desert Palace', volume: 12, revenue: 980000, share: '25%' },
  { name: 'Andaman Private Island Charter', volume: 6, revenue: 650000, share: '17%' },
  { name: 'Leh Ladakh High Altitude Luxury', volume: 4, revenue: 480000, share: '12%' },
]

export const mockFunnelData = [
  { step: 'Incoming Bespoke Inquiries', count: 142, percentage: '100%' },
  { step: 'Concierge Callback (<2h)', count: 118, percentage: '83.1%' },
  { step: 'Custom Proposal Dispatched', count: 76, percentage: '53.5%' },
  { step: 'Commercial Negotiation', count: 48, percentage: '33.8%' },
  { step: 'Final Confirmed Voyage', count: 37, percentage: '26.1%' },
]

export const mockAnalytics = {
  inquiryFunnel: {
    total: 142,
    contacted: 118,
    quoteSent: 76,
    converted: 37,
  },
  revenueByPackage: [
    { packageName: 'Kashmir Autumn', revenue: 1620000 },
    { packageName: 'Kerala Backwaters', revenue: 1170000 },
    { packageName: 'Rajasthan Royal', revenue: 980000 },
    { packageName: 'Andaman Charter', revenue: 650000 },
    { packageName: 'Leh Ladakh Luxury', revenue: 480000 },
  ],
  topSources: [
    { source: 'Instagram Ads', count: 45 },
    { source: 'Referral', count: 38 },
    { source: 'Direct Search', count: 32 },
    { source: 'Luxury Mag', count: 15 },
    { source: 'Other', count: 12 },
  ]
}
